version: '2.1'
volumes:
  yarn:
    external: true
  npmCache:
    external: true
  nodeModules:
    external: false
services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    build:
      dockerfile: Dockerfile-dev
      args:
        PACKAGE_INSTALLER: npm
    network_mode: "bridge"
    command: 'bash'
    volumes:
      - .:/app/user
      - nodeModules:/app/user/node_modules
      - npmCache:/root/.npm
      - yarn:/root/.yarn-cache
    environment:
      NODE_ENV: 'development'
    env_file:
      - ./.docker/common.env
      - ./.env
    ports:
      - '3000:3000'
      - '6006:6006'
    tty: true
    stdin_open: true
    read_only: false
